# This file was auto-generated by scrape_projections.py
# It contains the dictionary of scraped PROJ projections.

projections = { 'Adams Hemisphere in a Square': '+proj=adams_hemi +ellps=WGS84 +datum=WGS84 '
                                  '+units=m +no_defs',
  'Adams World in a Square I': '+proj=adams_ws1 +ellps=WGS84 +datum=WGS84 '
                               '+units=m +no_defs',
  'Adams World in a Square II': '+proj=adams_ws2 +ellps=WGS84 +datum=WGS84 '
                                '+units=m +no_defs',
  'Airocean': '+proj=airocean +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Airy': '+proj=airy +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Aitoff': '+proj=aitoff +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Albers Equal Area': '+proj=aea +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Apian Globular I': '+proj=apian +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'August Epicycloidal': '+proj=august +ellps=WGS84 +datum=WGS84 +units=m '
                         '+no_defs',
  'Azimuthal Equidistant': '+proj=aeqd +ellps=WGS84 +datum=WGS84 +units=m '
                           '+no_defs',
  'Bacon Globular': '+proj=bacon +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Bertin 1953': '+proj=bertin1953 +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Bipolar conic of western hemisphere': '+proj=bipc +ellps=WGS84 +datum=WGS84 '
                                         '+units=m +no_defs',
  'Boggs Eumorphic': '+proj=boggs +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Bonne (Werner lat_1=90)': '+proj=bonne +ellps=WGS84 +datum=WGS84 +units=m '
                             '+no_defs',
  'Cal Coop Ocean Fish Invest Lines/Stations': '+proj=calcofi +ellps=WGS84 '
                                               '+datum=WGS84 +units=m +no_defs',
  'Cassini (Cassini-Soldner)': '+proj=cass +ellps=WGS84 +datum=WGS84 +units=m '
                               '+no_defs',
  'Central Conic': '+proj=ccon +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Central Cylindrical': '+proj=cc +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Chamberlin Trimetric': '+proj=chamb +ellps=WGS84 +datum=WGS84 +units=m '
                          '+no_defs',
  'Collignon': '+proj=collg +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Colombia Urban': '+proj=col_urban +ellps=WGS84 +datum=WGS84 +units=m '
                    '+no_defs',
  'Compact Miller': '+proj=comill +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Craster Parabolic (Putnins P4)': '+proj=crast +ellps=WGS84 +datum=WGS84 '
                                    '+units=m +no_defs',
  'Denoyer Semi-Elliptical': '+proj=denoy +ellps=WGS84 +datum=WGS84 +units=m '
                             '+no_defs',
  'Eckert I': '+proj=eck1 +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Eckert II': '+proj=eck2 +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Eckert III': '+proj=eck3 +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Eckert IV': '+proj=eck4 +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Eckert V': '+proj=eck5 +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Eckert VI': '+proj=eck6 +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Equal Area Cylindrical': '+proj=cea +ellps=WGS84 +datum=WGS84 +units=m '
                            '+no_defs',
  'Equal Earth': '+proj=eqearth +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Equidistant Conic': '+proj=eqdc +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Equidistant Cylindrical (Plate Carrée)': '+proj=eqc +ellps=WGS84 '
                                            '+datum=WGS84 +units=m +no_defs',
  'Euler': '+proj=euler +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Fahey': '+proj=fahey +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Foucaut': '+proj=fouc +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Foucaut Sinusoidal': '+proj=fouc_s +ellps=WGS84 +datum=WGS84 +units=m '
                        '+no_defs',
  'Gall (Gall Stereographic)': '+proj=gall +ellps=WGS84 +datum=WGS84 +units=m '
                               '+no_defs',
  'Gauss-Schreiber Transverse Mercator (aka Gauss-Laborde Reunion)': '+proj=gstmerc '
                                                                     '+ellps=WGS84 '
                                                                     '+datum=WGS84 '
                                                                     '+units=m '
                                                                     '+no_defs',
  'General Oblique Transformation': '+proj=ob_tran +ellps=WGS84 +datum=WGS84 '
                                    '+units=m +no_defs',
  'General Sinusoidal Series': '+proj=gn_sinu +ellps=WGS84 +datum=WGS84 '
                               '+units=m +no_defs',
  'Geostationary Satellite View': '+proj=geos +ellps=WGS84 +datum=WGS84 '
                                  '+units=m +no_defs',
  'Ginsburg VIII (TsNIIGAiK)': '+proj=gins8 +ellps=WGS84 +datum=WGS84 +units=m '
                               '+no_defs',
  'Gnomonic': '+proj=gnom +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Goode Homolosine': '+proj=goode +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Guyou': '+proj=guyou +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'HEALPix': '+proj=healpix +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Hammer & Eckert-Greifendorff': '+proj=hammer +ellps=WGS84 +datum=WGS84 '
                                  '+units=m +no_defs',
  'Hatano Asymmetrical Equal Area': '+proj=hatano +ellps=WGS84 +datum=WGS84 '
                                    '+units=m +no_defs',
  'Icosahedral Snyder Equal Area': '+proj=isea +ellps=WGS84 +datum=WGS84 '
                                   '+units=m +no_defs',
  'International Map of the World Polyconic': '+proj=imw_p +ellps=WGS84 '
                                              '+datum=WGS84 +units=m +no_defs',
  'Interrupted Goode Homolosine': '+proj=igh +ellps=WGS84 +datum=WGS84 '
                                  '+units=m +no_defs',
  'Interrupted Goode Homolosine (Oceanic View)': '+proj=igh_o +ellps=WGS84 '
                                                 '+datum=WGS84 +units=m '
                                                 '+no_defs',
  'Interrupted Mollweide': '+proj=imoll +ellps=WGS84 +datum=WGS84 +units=m '
                           '+no_defs',
  'Interrupted Mollweide (Oceanic View)': '+proj=imoll_o +ellps=WGS84 '
                                          '+datum=WGS84 +units=m +no_defs',
  'Kavrayskiy V': '+proj=kav5 +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Kavrayskiy VII': '+proj=kav7 +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Krovak': '+proj=krovak +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Laborde': '+proj=labrd +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Lagrange': '+proj=lagrng +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Lambert Azimuthal Equal Area': '+proj=laea +ellps=WGS84 +datum=WGS84 '
                                  '+units=m +no_defs',
  'Lambert Conformal Conic': '+proj=lcc +ellps=WGS84 +datum=WGS84 +units=m '
                             '+no_defs',
  'Lambert Conformal Conic Alternative': '+proj=lcca +ellps=WGS84 +datum=WGS84 '
                                         '+units=m +no_defs',
  'Lambert Equal Area Conic': '+proj=leac +ellps=WGS84 +datum=WGS84 +units=m '
                              '+no_defs',
  'Larrivee': '+proj=larr +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Laskowski': '+proj=lask +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Lee Oblated Stereographic': '+proj=lee_os +ellps=WGS84 +datum=WGS84 '
                               '+units=m +no_defs',
  'Loximuthal': '+proj=loxim +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'McBride-Thomas Flat-Polar Parabolic': '+proj=mbtfpp +ellps=WGS84 '
                                         '+datum=WGS84 +units=m +no_defs',
  'McBryde-Thomas Flat-Polar Quartic': '+proj=mbtfpq +ellps=WGS84 +datum=WGS84 '
                                       '+units=m +no_defs',
  'McBryde-Thomas Flat-Polar Sine (No. 1)': '+proj=mbt_s +ellps=WGS84 '
                                            '+datum=WGS84 +units=m +no_defs',
  'McBryde-Thomas Flat-Polar Sinusoidal': '+proj=mbtfps +ellps=WGS84 '
                                          '+datum=WGS84 +units=m +no_defs',
  'McBryde-Thomas Flat-Pole Sine (No. 2)': '+proj=mbt_fps +ellps=WGS84 '
                                           '+datum=WGS84 +units=m +no_defs',
  'Mercator': '+proj=merc +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Miller Cylindrical': '+proj=mill +ellps=WGS84 +datum=WGS84 +units=m '
                        '+no_defs',
  'Miller Oblated Stereographic': '+proj=mil_os +ellps=WGS84 +datum=WGS84 '
                                  '+units=m +no_defs',
  'Modified Krovak': '+proj=mod_krovak +ellps=WGS84 +datum=WGS84 +units=m '
                     '+no_defs',
  'Modified Stereographic of 48 U.S.': '+proj=gs48 +ellps=WGS84 +datum=WGS84 '
                                       '+units=m +no_defs',
  'Modified Stereographic of Alaska': '+proj=alsk +ellps=WGS84 +datum=WGS84 '
                                      '+units=m +no_defs',
  'Modified Stereographic of the 50 U.S. states': '+proj=gs50 +ellps=WGS84 '
                                                  '+datum=WGS84 +units=m '
                                                  '+no_defs',
  'Mollweide': '+proj=moll +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Murdoch I': '+proj=murd1 +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Murdoch II': '+proj=murd2 +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Murdoch III': '+proj=murd3 +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Natural Earth': '+proj=natearth +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Natural Earth II': '+proj=natearth2 +ellps=WGS84 +datum=WGS84 +units=m '
                      '+no_defs',
  'Near-sided perspective': '+proj=nsper +ellps=WGS84 +datum=WGS84 +units=m '
                            '+no_defs',
  'Nell': '+proj=nell +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Nell-Hammer': '+proj=nell_h +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'New Zealand Map Grid (EPSG:27200)': '+proj=nzmg +ellps=WGS84 +datum=WGS84 '
                                       '+units=m +no_defs',
  'Nicolosi Globular': '+proj=nicol +ellps=WGS84 +datum=WGS84 +units=m '
                       '+no_defs',
  'Oblated Equal Area': '+proj=oea +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Oblique Cylindrical Equal Area': '+proj=ocea +ellps=WGS84 +datum=WGS84 '
                                    '+units=m +no_defs',
  'Oblique Mercator': '+proj=omerc +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Oblique Stereographic Alternative': '+proj=sterea +ellps=WGS84 +datum=WGS84 '
                                       '+units=m +no_defs',
  'Ortelius Oval': '+proj=ortel +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Orthographic': '+proj=ortho +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Patterson': '+proj=patterson +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Peirce Quincuncial': '+proj=peirce_q +ellps=WGS84 +datum=WGS84 +units=m '
                        '+no_defs',
  'Perspective Conic': '+proj=pconic +ellps=WGS84 +datum=WGS84 +units=m '
                       '+no_defs',
  'Polyconic (American)': '+proj=poly +ellps=WGS84 +datum=WGS84 +units=m '
                          '+no_defs',
  'Putnins P1': '+proj=putp1 +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Putnins P2': '+proj=putp2 +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Putnins P3': '+proj=putp3 +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  "Putnins P3'": '+proj=putp3p +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  "Putnins P4'": '+proj=putp4p +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Putnins P5': '+proj=putp5 +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  "Putnins P5'": '+proj=putp5p +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Putnins P6': '+proj=putp6 +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  "Putnins P6'": '+proj=putp6p +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Quadrilateralized Spherical Cube': '+proj=qsc +ellps=WGS84 +datum=WGS84 '
                                      '+units=m +no_defs',
  'Quartic Authalic': '+proj=qua_aut +ellps=WGS84 +datum=WGS84 +units=m '
                      '+no_defs',
  'Rectangular Polyconic': '+proj=rpoly +ellps=WGS84 +datum=WGS84 +units=m '
                           '+no_defs',
  'Robinson': '+proj=robin +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Roussilhe Stereographic': '+proj=rouss +ellps=WGS84 +datum=WGS84 +units=m '
                             '+no_defs',
  'S2': '+proj=s2 +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Sinusoidal (Sanson-Flamsteed)': '+proj=sinu +ellps=WGS84 +datum=WGS84 '
                                   '+units=m +no_defs',
  'Space Oblique Mercator (SOM)': '+proj=som +ellps=WGS84 +datum=WGS84 '
                                  '+units=m +no_defs',
  'Space oblique for LANDSAT': '+proj=lsat +ellps=WGS84 +datum=WGS84 +units=m '
                               '+no_defs',
  'Space oblique for MISR': '+proj=misrsom +ellps=WGS84 +datum=WGS84 +units=m '
                            '+no_defs',
  'Spherical Cross-track Height': '+proj=sch +ellps=WGS84 +datum=WGS84 '
                                  '+units=m +no_defs',
  'Spilhaus': '+proj=spilhaus +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Stereographic': '+proj=stere +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Swiss Oblique Mercator': '+proj=somerc +ellps=WGS84 +datum=WGS84 +units=m '
                            '+no_defs',
  'Tilted perspective': '+proj=tpers +ellps=WGS84 +datum=WGS84 +units=m '
                        '+no_defs',
  'Times': '+proj=times +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Tissot': '+proj=tissot +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Tobler-Mercator': '+proj=tobmerc +ellps=WGS84 +datum=WGS84 +units=m '
                     '+no_defs',
  'Transverse Central Cylindrical': '+proj=tcc +ellps=WGS84 +datum=WGS84 '
                                    '+units=m +no_defs',
  'Transverse Cylindrical Equal Area': '+proj=tcea +ellps=WGS84 +datum=WGS84 '
                                       '+units=m +no_defs',
  'Transverse Mercator': '+proj=tmerc +ellps=WGS84 +datum=WGS84 +units=m '
                         '+no_defs',
  'Two Point Equidistant': '+proj=tpeqd +ellps=WGS84 +datum=WGS84 +units=m '
                           '+no_defs',
  'Universal Polar Stereographic': '+proj=ups +ellps=WGS84 +datum=WGS84 '
                                   '+units=m +no_defs',
  'Universal Transverse Mercator (UTM)': '+proj=utm +ellps=WGS84 +datum=WGS84 '
                                         '+units=m +no_defs',
  'Urmaev Flat-Polar Sinusoidal': '+proj=urmfps +ellps=WGS84 +datum=WGS84 '
                                  '+units=m +no_defs',
  'Urmaev V': '+proj=urm5 +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Vitkovsky I': '+proj=vitk1 +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Wagner I (Kavrayskiy VI)': '+proj=wag1 +ellps=WGS84 +datum=WGS84 +units=m '
                              '+no_defs',
  'Wagner II': '+proj=wag2 +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Wagner III': '+proj=wag3 +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Wagner IV': '+proj=wag4 +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Wagner V': '+proj=wag5 +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Wagner VI': '+proj=wag6 +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Wagner VII': '+proj=wag7 +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Web Mercator / Pseudo Mercator': '+proj=webmerc +ellps=WGS84 +datum=WGS84 '
                                    '+units=m +no_defs',
  'Werenskiold I': '+proj=weren +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Winkel I': '+proj=wink1 +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Winkel II': '+proj=wink2 +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'Winkel Tripel': '+proj=wintri +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'rHEALPix': '+proj=rhealpix +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  'van der Grinten (I)': '+proj=vandg +ellps=WGS84 +datum=WGS84 +units=m '
                         '+no_defs',
  'van der Grinten II': '+proj=vandg2 +ellps=WGS84 +datum=WGS84 +units=m '
                        '+no_defs',
  'van der Grinten III': '+proj=vandg3 +ellps=WGS84 +datum=WGS84 +units=m '
                         '+no_defs',
  'van der Grinten IV': '+proj=vandg4 +ellps=WGS84 +datum=WGS84 +units=m '
                        '+no_defs'}
